### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by noonien** [Thunderbub/Vitality#2]
Adauga un fisier README.md, scris in formatul [markdown](https://help.github.com/articles/github-flavored-markdown/) in care sa ai niste descrieri despre proiect, si eventual instructiuni pentru building, running.

**Comment by noonien** [comment]
Mai toate proiectele de pe github au README.md, dar daca vrei un exemplu minimal, gasesti [aici](https://github.com/noonien/go-trakt/blob/master/README.md).

**Comment by noonien** [comment]
Aproape, citeste link-ul care ti l-am dat la markdown, si fa titlurile sa arate calumea. Gasesti [aici](https://jbt.github.io/markdown-editor/) un previewer.

**Comment by thunderbub** [comment]
Iam mai facut niste modificari.
