### ISSUE TITLE
Fisiere binare si swap

### ISSUE THREAD

**Issue by noonien** [Thunderbub/Vitality#3]
Fisierele [binare](https://github.com/Thunderbub/Vitality/blob/master/c%2B%2B/helloworld) si [swap](https://github.com/Thunderbub/Vitality/blob/master/c%2B%2B/first.c~) nu au ce cauta in repository, ori le adaugi intr-un [.gitignore](https://help.github.com/articles/ignoring-files/) ori cand faci `git add` nu le adaugi.

Acum, daca faci un commit nou, cu fisierele sterse, ele tot se afla in history la repo, invata cum sa faci un [git commit --amend](https://www.atlassian.com/git/tutorials/rewriting-history/git-commit--amend).

Atentie, `git commit --amend` nu trebuie folosit dupa ce ai facut git push, de data asta e ok. Dupa ce faci amend, faci un `git push -f` ca sa urci pe github din nou.

**Comment by thunderbub** [comment]
Fisierele au fost sterse prin commit amend.
